import { ipcMain } from 'electron'
import { IPC } from '@shared/ipc-channels'
import { ensureCaInstalled, lastCaInstallResult } from '../services/ca-install'
import { deviceService } from '../services/device'
import { proxyService } from '../services/proxy'
import { bus } from '../utils/event-bus'
import { safe } from '../utils/result'

export function registerProxyIpc(): void {
  ipcMain.handle(IPC.proxy.getStatus, () => proxyService.getStatus())
  ipcMain.handle(IPC.proxy.start, () => safe('proxy.start', () => proxyService.start()))
  ipcMain.handle(IPC.proxy.stop, () => safe('proxy.stop', () => proxyService.stop()))

  ipcMain.handle(IPC.proxy.listRequests, (_e, raw: unknown) =>
    safe('proxy.listRequests', () => {
      const opts = (raw ?? {}) as { limit?: number; offset?: number; search?: string }
      return proxyService.listRequests(opts)
    })
  )

  ipcMain.handle(IPC.proxy.getRequest, (_e, raw: unknown) =>
    safe('proxy.getRequest', () => {
      if (typeof raw !== 'string') throw new Error('Request id must be a string')
      return proxyService.getRequest(raw)
    })
  )

  ipcMain.handle(IPC.proxy.clearRequests, () =>
    safe('proxy.clearRequests', () => proxyService.clearRequests())
  )

  ipcMain.handle(IPC.proxy.exportHar, (_e, raw: unknown) =>
    safe('proxy.exportHar', () => {
      if (typeof raw !== 'string') throw new Error('File path must be a string')
      return proxyService.exportHar(raw)
    })
  )

  // Retrigger the CA install flow against the currently active device.
  // For non-rooted devices this re-pushes the cert and re-launches the
  // CertInstaller activity, which is exactly what users need when they
  // accidentally dismissed the dialog the first time.
  ipcMain.handle(IPC.proxy.reinstallCa, () =>
    safe('proxy.reinstallCa', async () => {
      const device = deviceService.getActive()
      if (!device || device.state !== 'online') {
        throw new Error('No online device to install the certificate onto.')
      }
      if (proxyService.getStatus().state !== 'running') {
        throw new Error('Start the proxy first — the CA cert is generated by mitmproxy.')
      }
      const result = await ensureCaInstalled(device.serial)
      bus.emit('proxy:caInstall', result)
      return result
    })
  )

  ipcMain.handle(IPC.proxy.getCaInstallResult, () =>
    safe('proxy.getCaInstallResult', () => lastCaInstallResult())
  )
}
